language: d
sudo: false
dist: trusty

os:
    - linux
    - osx

d:
    - dmd-2.080.0
    - dmd-2.079.1
    - dmd-2.078.3
    - dmd-2.077.1
    - dmd-2.076.1
    - ldc-1.9.0 # 2.079.1
    - ldc-1.8.0 # 2.078.3
    - ldc-1.7.0 # 2.077.1
    - ldc-1.6.0 # 2.076.1

script:
    - dub test -b unittest-cov --compiler=${DC}

after_success:
    - bash <(curl -s https://codecov.io/bash)
