language: d
sudo: false
dist: trusty

os:
    - linux
    - osx

d:
    - dmd-2.082.1 # 2018 Oct 10 / Add UDAs on function parameters.
    - dmd-2.081.2 # 2018 Aug 12 / Add expression-based contracts.
    - dmd-2.080.1 # 2018 Jun 7
    - dmd-2.079.1 # 2018 Apr 14
    - ldc-1.12.0 # 2.082.1
    - ldc-1.11.0 # 2.081.2
    - ldc-1.10.0 # 2.080.1
    - ldc-1.9.0 # 2.079.1

script:
    - dub test -b unittest-cov --compiler=${DC}

after_success:
    - bash <(curl -s https://codecov.io/bash)
