language: d
sudo: false
dist: trusty

os:
    - linux
    - osx

d:
    - dmd-2.077.1
    - dmd-2.076.1

script:
    - dub test -b unittest-cov --compiler=${DC}

after_success:
    - bash <(curl -s https://codecov.io/bash)
